### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by Just-silent** [THU-KEG/KoPL#1]
如果想使用该工具，便需要对应的知识，这块知识的搭建复杂吗？需要建立在表现较好的信息抽取的基础上吧

**Comment by ShulinCao** [comment]
目前KoPL的使用需要搭建好的知识库，具体可以参考 https://kopl.xlore.cn/doc/4_helloworld.html 。关于知识库的搭建：可以通过文本的信息抽取得到，也可以使用已有的知识库（如Freebase, Wikidata, DBpedia等），比如我们在示例里使用的是Wikidata子集。

**Comment by Just-silent** [comment]
> 目前KoPL的使用需要搭建好的知识库，具体可以参考 https://kopl.xlore.cn/doc/4_helloworld.html 。关于知识库的搭建：可以通过文本的信息抽取得到，也可以使用已有的知识库（如Freebase, Wikidata, DBpedia等），比如我们在示例里使用的是Wikidata子集。

好的，谢谢您，我目前需要在特殊领域的小预料下做一个具有知识推理能力的问答系统，对你们提供的KoPL很感兴趣，感觉难点是不是在于信息抽取这块（估计抽取误差会很大），不知道你有什么好的建议？

**Comment by Just-silent** [comment]
或者知识图谱能不能转换存储到咱们这种存储结构

**Comment by ShulinCao** [comment]
你们的语料是什么结构的

**Comment by Just-silent** [comment]
> 你们的语料是什么结构的

我们目前的数据是在图谱里存的图结构，原始数据是从现场实时读取的表结构，不知能不能通过一种方式转换成KoPL的存储数据

**Comment by ShulinCao** [comment]
应该是可以的，按https://kopl.xlore.cn/doc/4_helloworld.html 这个格式

**Comment by Just-silent** [comment]
> 应该是可以的，按https://kopl.xlore.cn/doc/4_helloworld.html 这个格式

好的，谢谢您
